apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccountName }}
  labels:
    {{- include "k-logs-test.labels" . | nindent 4 }}
{{- with .Values.promGateway }}
    {{- toYaml .labels | nindent 4 }}
{{ end }}
