apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  annotations:
    {}
  labels:
    app: prometheus-pushgateway
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-pushgateway
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
      annotations:
        {}
    spec:
      serviceAccountName: prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
