version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.6

    working_directory: /go/src/github.com/nullck/k-logs-test
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make test-ci
