apiVersion: v1
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'k_logs'
      static_configs:
      - targets: ['prometheus-pushgateway:9091']
kind: ConfigMap
metadata:
  name: prometheus-cm
